framework:
    cache:
        # Unique name of your app: used to compute stable namespaces for cache keys.
        prefix_seed: storno

        # Uses filesystem in dev, Redis in prod
        # The data in this cache should persist between deploys.
        app: cache.adapter.filesystem

when@prod:
    framework:
        cache:
            app: cache.adapter.redis
            default_redis_provider: '%env(REDIS_URL)%'
