apiVersion: v1
kind: Service
metadata:
  name: {{ include "storno.centrifugoServiceName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "storno.componentLabels" (dict "component" "centrifugo" "context" .) | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "storno.componentSelectorLabels" (dict "component" "centrifugo" "context" .) | nindent 4 }}
  ports:
    - name: http
      port: 8000
      targetPort: http
      protocol: TCP
