{{- if .Values.mysql.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "storno.mysqlServiceName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "storno.componentLabels" (dict "component" "mysql" "context" .) | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "storno.componentSelectorLabels" (dict "component" "mysql" "context" .) | nindent 4 }}
  ports:
    - name: mysql
      port: 3306
      targetPort: mysql
      protocol: TCP
{{- end }}
