apiVersion: v1
kind: Service
metadata:
  name: {{ include "storno.redisServiceName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "storno.componentLabels" (dict "component" "redis" "context" .) | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "storno.componentSelectorLabels" (dict "component" "redis" "context" .) | nindent 4 }}
  ports:
    - name: redis
      port: 6379
      targetPort: redis
      protocol: TCP
